CREATE TABLE USER
(
  UserID INT NOT NULL,
  Password VARCHAR(100) NOT NULL,
  FirstName VARCHAR(100) NOT NULL,
  LastName VARCHAR(100),
  MiddleName VARCHAR(100),
  Email VARCHAR(100) NOT NULL,
  PRIMARY KEY (UserID),
  UNIQUE (Email)
);

CREATE TABLE CITY
(
  CityID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  State VARCHAR(100) NOT NULL,
  Country VARCHAR(100) NOT NULL,
  PRIMARY KEY (CityID)
);

CREATE TABLE AIRPORT
(
  AirportID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  CityID INT NOT NULL,
  PRIMARY KEY (AirportID),
  FOREIGN KEY (CityID) REFERENCES CITY(CityID)
);

CREATE TABLE HOTEL
(
  HotelID INT NOT NULL,
  HotelName VARCHAR(100) NOT NULL,
  CityID INT NOT NULL,
  PRIMARY KEY (HotelID),
  FOREIGN KEY (CityID) REFERENCES CITY(CityID)
);

CREATE TABLE ROOM_TYPES
(
  TypeName VARCHAR(100) NOT NULL,
  Count INT NOT NULL,
  Price FLOAT NOT NULL,
  HotelID INT NOT NULL,
  PRIMARY KEY (TypeName, HotelID),
  FOREIGN KEY (HotelID) REFERENCES HOTEL(HotelID)
);

CREATE TABLE AGENCY (
  AgencyID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  PRIMARY KEY (AgencyID)
);

CREATE TABLE AGENT
(
  AgentID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  Exp INT NOT NULL,
  AgencyID INT NOT NULL,
  PRIMARY KEY (AgentID, AgencyID),
  FOREIGN KEY (AgencyID) REFERENCES AGENCY(AgencyID)
);

CREATE TABLE PACKAGE
(
  PackageID INT NOT NULL,
  Title VARCHAR(100) NOT NULL,
  AgencyID INT NOT NULL,
  PRIMARY KEY (PackageID, AgencyID),
  FOREIGN KEY (AgencyID) REFERENCES AGENCY(AgencyID)
);

CREATE TABLE AIRLINE
(
  AirlineID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  PRIMARY KEY (AirlineID)
);

CREATE TABLE BUS
(
  BusID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  Seats INT NOT NULL,
  Fare FLOAT NOT NULL,
  DeptDateTime DATE NOT NULL,
  ArrDateTime DATE NOT NULL,
  DepartureCity INT NOT NULL,
  ArrivalCity INT NOT NULL,
  PRIMARY KEY (BusID),
  FOREIGN KEY (DepartureCity) REFERENCES CITY(CityID),
  FOREIGN KEY (ArrivalCity) REFERENCES CITY(CityID)
);

CREATE TABLE INCL_CITY
(
  ArrDate DATE NOT NULL,
  CityID INT NOT NULL,
  PackageID INT NOT NULL,
  AgencyID INT NOT NULL,
  PRIMARY KEY (CityID, PackageID, AgencyID),
  FOREIGN KEY (CityID) REFERENCES CITY(CityID),
  FOREIGN KEY (PackageID, AgencyID) REFERENCES PACKAGE(PackageID, AgencyID)
);

CREATE TABLE INCL_BUS
(
  BusID INT NOT NULL,
  PackageID INT NOT NULL,
  AgencyID INT NOT NULL,
  PRIMARY KEY (BusID, PackageID, AgencyID),
  FOREIGN KEY (BusID) REFERENCES BUS(BusID),
  FOREIGN KEY (PackageID, AgencyID) REFERENCES PACKAGE(PackageID, AgencyID)
);

CREATE TABLE INCL_ROOM
(
  TypeName VARCHAR(100) NOT NULL,
  HotelID INT NOT NULL,
  PackageID INT NOT NULL,
  AgencyID INT NOT NULL,
  PRIMARY KEY (TypeName, HotelID, PackageID, AgencyID),
  FOREIGN KEY (TypeName, HotelID) REFERENCES ROOM_TYPES(TypeName, HotelID),
  FOREIGN KEY (PackageID, AgencyID) REFERENCES PACKAGE(PackageID, AgencyID)
);

CREATE TABLE BOOKING
(
  BookingID INT NOT NULL,
  UserID INT NOT NULL,
  PRIMARY KEY (BookingID),
  FOREIGN KEY (UserID) REFERENCES USER(UserID)
);

CREATE TABLE PAYMENT
(
  PaymentID INT NOT NULL,
  Method VARCHAR(100) NOT NULL,
  TransactionDateTime DATE NOT NULL,
  Amount FLOAT NOT NULL,
  BookingID INT NOT NULL,
  PRIMARY KEY (PaymentID),
  FOREIGN KEY (BookingID) REFERENCES BOOKING(BookingID)
);

CREATE TABLE BOOKS_BUS
(
  BookingID INT NOT NULL,
  BusID INT NOT NULL,
  PRIMARY KEY (BookingID, BusID),
  FOREIGN KEY (BookingID) REFERENCES BOOKING(BookingID),
  FOREIGN KEY (BusID) REFERENCES BUS(BusID)
);

CREATE TABLE BOOKS_ROOM
(
  CheckInDate DATE NOT NULL,
  CheckOutDate DATE NOT NULL,
  Quantity INT NOT NULL,
  BookingID INT NOT NULL,
  TypeName VARCHAR(100) NOT NULL,
  HotelID INT NOT NULL,
  PRIMARY KEY (BookingID, TypeName, HotelID),
  FOREIGN KEY (BookingID) REFERENCES BOOKING(BookingID),
  FOREIGN KEY (TypeName, HotelID) REFERENCES ROOM_TYPES(TypeName, HotelID)
);

CREATE TABLE BOOKS_PACKAGE
(
  BookingID INT NOT NULL,
  PackageID INT NOT NULL,
  AgencyID INT NOT NULL,
  PRIMARY KEY (BookingID),
  FOREIGN KEY (BookingID) REFERENCES BOOKING(BookingID),
  FOREIGN KEY (PackageID, AgencyID) REFERENCES PACKAGE(PackageID, AgencyID)
);

CREATE TABLE FLIGHT
(
  FlightID INT NOT NULL,
  Seats INT NOT NULL,
  Fare FLOAT NOT NULL,
  DepartureTime DATE NOT NULL,
  ArrivalTime DATE NOT NULL,
  AirlineID INT NOT NULL,
  DepartureAirport INT NOT NULL,
  ArrivalAirport INT NOT NULL,
  PRIMARY KEY (FlightID),
  FOREIGN KEY (AirlineID) REFERENCES AIRLINE(AirlineID),
  FOREIGN KEY (DepartureAirport) REFERENCES AIRPORT(AirportID),
  FOREIGN KEY (ArrivalAirport) REFERENCES AIRPORT(AirportID)
);

CREATE TABLE INCL_FLIGHT
(
  FlightID INT NOT NULL,
  PackageID INT NOT NULL,
  AgencyID INT NOT NULL,
  PRIMARY KEY (FlightID, PackageID, AgencyID),
  FOREIGN KEY (FlightID) REFERENCES FLIGHT(FlightID),
  FOREIGN KEY (PackageID, AgencyID) REFERENCES PACKAGE(PackageID, AgencyID)
);

CREATE TABLE BOOKS_FLIGHT
(
  BookingID INT NOT NULL,
  FlightID INT NOT NULL,
  PRIMARY KEY (BookingID, FlightID),
  FOREIGN KEY (BookingID) REFERENCES BOOKING(BookingID),
  FOREIGN KEY (FlightID) REFERENCES FLIGHT(FlightID)
);